### ISSUE TITLE
Model loader

### ISSUE THREAD

**Issue by tana** [tana/Mondeto#33]
Load 3D model file (e.g. glTF) and place into virtual space.

```yaml
objects:
  -
    position: !vec [0, 0, 0]
    rotation: !quat [1, 0, 0, 0]
    tag: [model]
    model: !load_file "box.gltf"
```
