### ISSUE TITLE
Primitive (and glTF?) scaling

### ISSUE THREAD

**Issue by tana** [tana/Mondeto#35]
Add some field to change scale of primitives and loaded models.
```yaml
objects
  - position: !vec [0, 0, 0]
    rotation: !euler [0, 0, 0]
    tags: [cube, collision]
    scale: !vec [10, 0.1, 10]
```
(A `cube` is no longer a cube when scaled?)
