### ISSUE TITLE
Scene description format

### ISSUE THREAD

**Issue by tana** [tana/Mondeto#9]
Text-based file for defining scenes.
Current plan: [YAML](https://yaml.org/)-based format corresponding directly to object structure
```yaml
objects:
  -
    position: !vec [0, 0, 0] # Tag distinguishes vector from array
    rotation: !quat [1, 0, 0, 0]
    primitive: plane 
  -
    position: !vec [1.5, 0, 0]
    rotation: !euler [10, 0, 0] # Converted into a quaternion (!quat)
    model: !load_file "teapot.gltf" # Load local file and create a BlobHandle
```
It relies on YAML [tags](https://yaml.org/spec/1.2/spec.html#id2764295) to represent vector, quaternion or BlobHandles.
